eiffel-community/etos-environment-provider

src/environment_provider/execution_space/list.py
fixes: eiffel-community/etos#20
Pass RABBITMQ_SSL to the instructions for execution space and ETR.
It's quite bad to implement the RABBITMQ parameters this statically. Could be done more dynamically.
Let's look at it in the future.
It's possible to run ETOS even without SSL enabled RabbitMQ.
None
by …
=> Pass RABBITMQ_SSL to instructions for ETR

src/environment_provider/environment_provider.py, src/environment_provider/lib/registry.py, src/environment_provider/webserver.py
fixes: eiffel-community/etos#68
Celery instanciates the class when it is registered causing problems
with shared memory, since every task is executed in the same instance.
None
It is possible to execute several environment providers at the same time as well as concurrently and get what it is you are requesting, instead of something magical.
None
work with …
=> Move environment provider task to a function instead of task class.

src/environment_provider/lib/registry.py, src/environment_provider/webserver.py
N/A
Fix a problem with providers being reused improperly between executions.
The problem is that the providers are stored globally with the first configuration and that configuration is never reset. This means that when the first configuration is done, then all others will use that same configuration.
Also added some more logging that was used to debug this problem and made sure that the web server part of the environment provider logs using the logging service in ETOS library.
None
The ability to use different providers than the first person executing :)
None
indicated in …
=> Fix a bug with providers being reused improperly

.gitignore, src/environment_provider/iut/iut_provider.py, src/environment_provider/iut/prepare.py
Fixes eiffel-community/etos#77
- Re-allocated memory for checked out IUT data, that is passed by ref.
- Fixed bug calculation of which IUTs to check-in when prepare step is completed
- Unrelated update to .gitignore
None
A working prepare step with proper check-out and check-in of OUTs
None
by me, …
=> Fix broken prepare step in Environment Provider

src/environment_provider/environment_provider.py
fixes: eiffel-community/etos#80
Make sure that one can configure the wait timeouts in the environment provider.
We could use another system other than environment variables, which might be a bit clearer.
However since we are already using environment variables, it feels correct to use them here as well.
Able to configure wait times in ETOS. Sometimes it's okay to wait more than 10 seconds for an IUT.
None
license and I …
=> Support configurating the wait timeouts

src/environment_provider/external_iut/__init__.py, src/environment_provider/external_iut/provider.py, test-requirements.txt, tests/external_iut/__init__.py, tests/external_iut/test_external_iut.py, tests/library/__init__.py, tests/library/fake_server.py, tox.ini
Implemented an external IUT provider service for requesting IUTs from external APIs.
Note that this implementation is done but not tested in real life. It is also not enabled.
We will implement this feature in steps so that the size of the update is smaller.
There are multiple designs that were considered. The one we use now delegates most of the work to the external provider so that there is more control and less red tape.
This allows users that need complex JSONTas providers to create a separate service for their work instead. Making it easier to debug and understand what goes wrong.
There is added complexity in the environment provider until we've done away with or separated out the JSONTas provider code.
By making a …
=> Add a new IUT provider handler for external IUTs

src/environment_provider/backend/subsuite.py, src/environment_provider/environment_provider.py, src/environment_provider/webserver.py, tests/backend/test_sub_suite.py, tests/test_webserver.py
This PR is the first of several clean-up changes that will be created. I do them in steps to make reviewing easier.
This is done in preparation for the external provider change that is on its way ( #38 )
By making the endpoints cleaner, we can make the external provider changes easier.
There are multiple designs, I chose the one where we
1. Reduce the size of webserver.py the most.
2. Make it easier to test.
Makes it easier to understand what is going on in the webserver.py file and makes it a lot easier to test.
Some code-jumping will be involved. With proper function naming this will be mitigated.
have …
=> Cleanup subsuite endpoint

src/environment_provider/external_execution_space/__init__.py, src/environment_provider/external_execution_space/provider.py, tests/external_execution_space/__init__.py, tests/external_execution_space/test_external_execution_space.py, tests/library/fake_server.py
This provider is unused at the moment and more or less a copy of the external IUT provider.
We might want to look into merging all external provider constructs later, if we don't have any big differences.
The reason I did not do that in this PR is because when we start testing these new providers, we might find issues that only have to be fixed in a specific provider.
Allows users to create complex providers without writing crazy JSONTas code.
None
of my …
=> Add an external execution space provider

docs/conf.py, src/environment_provider/external_log_area/__init__.py, src/environment_provider/external_log_area/provider.py, tests/external_log_area/__init__.py, tests/external_log_area/test_external_log_area.py
This provider is unused at the moment and more or less a copy of the external IUT provider.
We might want to look into merging all external provider constructs later, if we don't have any big differences.
The reason I did not do that in this PR is because when we start testing these new providers, we might find issues that only have to be fixed in a specific provider.
Allows users to create complex providers without writing crazy JSONTas code.
None
of my …
=> Add an external log area provider

src/environment_provider/splitter/split.py, tests/splitter/test_splitter.py
eiffel-community/etos#130
Make sure we always assign at least 1 IUT per testrunner.
You could probably work someting into the whole tound expression but a simple if 0 then 1 was simpler.
A working environment provider
None
permitted to submit …
=> Make sure to never assign 0 IUTs to a testrunner.

src/environment_provider/environment_provider.py, src/environment_provider/middleware/json_translator.py, src/environment_provider/middleware/require_json.py
Fixes: eiffel-community/etos#124
Environment provider will now send an environment defined for each sub suite (aka. environment) that has been checked out with a URI to the environment provider where that environment can be accessed.
None
Traceability
None
by me, under the same open source license …
=> Send environment defined events for each sub suite

.gitignore, setup.cfg, src/environment_provider/environment_provider.py, src/environment_provider/lib/graphql.py, src/execution_space_provider/utilities/external_provider.py, src/execution_space_provider/utilities/jsontas_provider.py, src/iut_provider/utilities/external_provider.py, src/iut_provider/utilities/jsontas_provider.py, src/iut_provider/utilities/prepare.py, src/log_area_provider/utilities/external_provider.py, src/log_area_provider/utilities/jsontas_provider.py
fixes: eiffel-community/etos#147
Added the sending of activity events in the environment provider.
We send one overarching activity that links to the ESR activity and then one activity for each test suite, which in turn sends an activity for each provider (with an extra prepare for the IUT provider).
The environments sent by the environment provider now links to the suite-activity instead which will break the ESR.
There are multiple. Only sending one activity for the environment provider instead of one for each suite was denied since we want to be able to trace the completion of environments that the ESR tracks.
Wanted to add an activity for the prepare steps, but that will make it harder on the external providers.
The environment events could be kept as they were until we are ready to …
=> Add activity events

src/environment_provider/environment_provider.py, src/environment_provider/lib/test_suite.py, src/environment_provider/splitter/split.py, tests/test_environment_provider.py, tox.ini
fixes: eiffel-community/etos#22
Attempt to enable sequential execution of sub suites in the environment provider.
Many. It feels like we are trying to solve too many things using the same logic. I want to investigate how this can be done much better depending on which situation we are in to make it much more clear.
This change will allow us to execute test suites with different test runners but not that many available IUTs.
The problem with sequential execution in ETOS is when we are having multiple test runners in one suite. I want to be able to split up the IUTs based on what percentage of the total number of tests there are for each test runner, but I also want to be able to check out a single IUT and wait for another to become available. I don't know how to solve this in an …
=> Enable sequential execution of sub suites

src/environment_provider/environment_provider.py
eiffel-community/etos#148
Add some more failure information when failing to create a full environment
None
Better information when stuff goes wrong
There could be duplicate information if an external provider also gives the failure information, but I don't think that's such a big problem.
by me, under …
=> Add some failure information when failing to create environment

src/environment_provider/lib/registry.py
eiffel-community/etos#50
Remove the logs that show the data from provider JSON files. The provider JSON files may contain password that should be encrypted and should not be logged.
I would love to have the data encrypted before adding it to the environment provider, but that cannot be guaranteed sadly.
Less sensitive data.
None
work with modifications, whether …
=> Remove logs that may contain sensitive data

src/environment_provider/environment_provider.py, src/execution_space_provider/utilities/instructions.py
fixes a problem with: #79 
Make sure that we still save the sub suite under the identifier key in Redis.
We are going to fix this so that it is no longer necessary in the ETR, but I don't want to break the environment provider before fixing it in ETR.
This will make sure that we still work while working on ETR.
None. But we really should clean up these redis writes later, when we don't need them anymore.
license and I have …
=> Change ENVIRONMENT_ID so as to not conflict with identifier

manifests/base/api/deployment.yaml, manifests/base/api/service-account.yaml, manifests/base/api/service.yaml, manifests/base/kustomization.yaml, manifests/base/worker/deployment.yaml, manifests/base/worker/service-account.yaml
eiffel-community/etos#188
Add manifest files to environment provider
We could keep all manifest files in the ETOS repository, but I think letting each component decide on its own versions and having the ETOS repository set the release versions is the correct way.
Kustomize is easier to handle and built into kubectl
None really
work with modifications, whether …
=> Add kustomization manifest files

src/execution_space_provider/utilities/external_provider.py
N/A
Send the default instructions to external providers.
I thought about sending them in using the JSON structure, but the defaults are added from the environment provider.
There's also the `parameters` field in the instructions which is not passed to the provider, since they have no defaults yet.
This will allow the external provider to work better with the environment provider, without many duplicate variables.
We are passing a lot of information.
of my knowledge, is covered under …
=> Send default instructions to external provider

src/environment_provider_api/backend/environment.py, tests/backend/test_environment.py, tests/test_environment_provider.py, tests/test_webserver_environment.py
- [Abort running suites using DELETE request](https://github.com/eiffel-community/etos/issues/209)
The "sub_suites" is not a valid key. The response was empty, and therefore the sub_suite loop was never executed. This prevented environment checkin from functioning properly.
by me, under the same open …
=> Remove subsuite loop from release_full_environment

src/execution_space_provider/utilities/external_provider.py, src/execution_space_provider/utilities/list.py
fixes: eiffel-community/etos#224
Remove all calls to `etos_lib.debug.environment_provider` which would raise an exception if the ETOS_ENVIRONMENT_PROVIDER environment variable is not set.
None. This variable is no longer needed.
None, but we should also remove it from the etos library.
by me, under …
=> Don't pass non-existing environment provider host

src/execution_space_provider/utilities/external_provider.py, src/iut_provider/utilities/external_provider.py, src/log_area_provider/utilities/external_provider.py
None
Always retry stop requests to external providers even if they receive connection refused errors.
If a provider is shutting down due to a restart, then we need to retry the stop request as to not leave any environment dangling after an ETOS testrun.
We could do a deeper analysis of the actual problem, but I don't really know how to do that without any sort of health-check mechanisms. And the restarting of the provider service is a difficult problem to detect.
If the retry timer is long, then we will hang until that timer expires in a case where the provider service is not expected to respond. However, since we should've already sent a Start and several Status requests to the service I think we can, relatively, safely assume that it should be up and running and this error is just an …
=> Make sure we do all in our power to release an environment

src/environment_provider/environment_provider.py
Make the default value for maximum amount configurable from the environment and the dataset. This allows for better control over the parallel-test feature in ETOS and gives the test operator the ability to tailor it specifically to their needs by setting the maximum_amount parameter in the dataset.
by …
=> Change default value for maximum amount

requirements.txt, setup.cfg
- https://github.com/eiffel-community/etos/issues/236
This change increments the version of etos_lib to 4.3.1 which corrects the format of opentelemetry_trace_id field in logstash entries (hex instead of dec).
permitted to submit under a different …
=> Step up etos_lib to 4.3.1

src/iut_provider/utilities/external_provider.py
When waiting/polling for a status change we sometime might hit a ConnectionError for various reasons and this is totally
fine as we simply continue to try again if a ConnectionError Exception is thrown. The issue is that the ConnectionError we're trying to catch is the one from `Builtin` and not the one from `requests`. This PR adds catching ConnectionErrors trown by requests, as this is the library used to do the status-request agaisnt the iut-provider.
of my knowledge, is covered …
=> Catch the ConnectionError exception from requests

src/environment_provider/environment.py, src/environment_provider/environment_provider.py
We have no garantue that all the logs have been downloaded when
we remove the main and subsuites from ETCD. This gives a potential
log area provider and the client a little more time to facilitate
download of the logs that were created last in the test run.
Also included a fix for an old annoing bug that provided a lackluster
error message to the user.
As this is a simple workaround no other design were considered
I tis unclear if the 30s sleep is enough for all situations
of my …
=> Add a 30s sleep as work around for log download race

src/environment_provider/environment.py
None
`release_full_environment` never ran `release_environment` because it tried to iterate over `sub_suites` in a dictionary that does not have that key. The default value is then an empty list which we don't iterate over.
Fix the code so that the correct key is retrieved from ETCD.
None
None
by me, …
=> Fix a problem where release_all is not run correctly

pyproject.toml, setup.py, src/environment_provider/lib/log_area.py
- https://github.com/eiffel-community/etos/issues/284
This change fixes the compatibility problem with tox/setuptools by moving the options from `pyproject.toml` to `setup.py`.
in the …
=> Compatibility fix for latest tox and setuptools

pyproject.toml, src/environment_provider/lib/config.py
eiffel-community/etos-suite-runner#67
eiffel-community/etos-library#41
Allow the use of the environment provider in environments that are not in Kubernetes, for instance when running tests.
permitted to submit under a different license), as …
=> Allow the environment provider to be used when not in Kubernetes

src/environment_provider/lib/config.py
Preparatory change for: eiffel-community/etos#306
If the environment provider was started by the environmentrequest controller, we should be able to run without the main suite activity and instead use the activity sent by the environment provider.
None really.
We might lose some traceability, but I think it's fine since the environment provider ActT does link to the main suite, just not the main activity.
license and I …
=> Remove dependency to the main context

.github/workflows/docker.yml, manifests/base/api/deployment.yaml, manifests/base/worker/deployment.yaml, tests/tercc.py
- https://github.com/eiffel-community/etos/issues/343
This pull request changes all docker image references from `nordix.org/eiffel` to `ghcr.io/eiffel-community`.
(c) …
=> Migrate container images to ghcr.io

.github/workflows/build-push.yml
- https://github.com/eiffel-community/etos/issues/351
This change update upload/download Github CI action to v4, since v3 is no longer supported.
(c) The contribution was …
=> Github workflow: use upload/download artifact action v4

pyproject.toml, requirements.txt, src/environment_provider/__init__.py
Since the logic to figure out in what environment the library is running
is very limited, we remove the logic and let it be handled better
somewhere outside of the library.
in the file; …
=> Remove in-library telemetry signals environment logic
