- requirements.txt
- setup.cfg
N/A
Upgrade gevent version to be inline with ETOS API.
Could keep version.
Versions are the same over projects
Not 100% tested
(c) The contribution was provided directly …
> Upgrade gevent version

- src/environment_provider/execution_space/instructions.py
fixes: #9 
Make sure to deepcopy the instructions before returning them to the execution_space_provider/list so that it is not overridden on the next execution.
None
Per-executor instructions are unique
None
permitted to submit under a different …
> Deepcopy datasubset instructions so that they are unique

- Dockerfile.workers
- src/worker.sh
eiffel-community/etos#52
Add a dockerfile for worker and add in worker script to container.
Added an environment variable for overriding celery worker parameters.
Could override how to execute with helm charts instead, but it seems to be working poorly.
Separation of concerns. Ability to make fixes in worker without involving the API.
Another docker to maintain.
license and I have the right under that license to submit …
> Add dockerfile for workers and add in worker script

- requirements.txt
- setup.cfg
- src/environment_provider/environment_provider.py
- src/environment_provider/iut/prepare.py
- src/environment_provider/lib/config.py
- src/environment_provider/lib/graphql.py
fixes: eiffel-community/etos#33
If a proper preparation step is provided, the environment provider
will attempt to prepare the IUT according to the JSONTas instruction.
More information will be added to documentation.
Also added the artifact events and tercc event to dataset for JSONTas
providers to use.
Added a check and get for an artifactPublished from GraphQL API.
ArtifactPublished can be None.
Updated to latest JSONTas which added features required for the
preparation to work.
There's a gray-zone in whether we should use JSONTas for execution when the intended use-case for JSONTas is to generate JSON.
Using JSONTas everywhere makes it easier for people to grasp. They only need to learn one language.
JSONTas might not support this execution style in the future.
Developer's Certificate …
> Add preparation stage to environment provider.

- src/environment_provider/iut/iut_definition.json
fixes: eiffel-community/etos#59
Added the 'stages', and 'steps' fields in the json schema.
Could describe the entirety of the 'steps' but that would be very difficult. We have to rely on the intelligence of our users.
Open ended and allows for easier customization in the different stages.
A bit more support for this case.
work with modifications, whether …
> Update IUT definition to account for the changes in prepare

- src/environment_provider/iut/prepare.py
N/A
Make sure that we can copy the dataset.
It's weird to remove the config and then reapply it, but it's fine.
It works.
None
(c) The contribution was provided directly …
> Make sure that we can make a copy of dataset

- Dockerfile
- Dockerfile.workers
eiffel-community/etos#36
Upgrade to python 3.9.0
None
Latest python, latest features.
None
person who …
> Upgrade environment provider to python 3.9.0

- Dockerfile.workers
- setup.cfg
- src/environment_provider/__init__.py
- src/environment_provider/environment_provider.py
- src/environment_provider/iut/prepare.py
- src/environment_provider/lib/celery.py
eiffel-community/etos#70
Add logging support from etos library 1.8.0
We should consider reducing the amount of logging done from separate tools.
Made it with all the logs in order to figure out what is needed.
The log output is now a rotating set of files that work well with filebeat and logstash.
We might lock ourselves into filebeat and logstash.
work with …
> Add logging support from etos library

- src/environment_provider/lib/celery.py
N/A
Remove extra setup_logging, resulting in double log output.
None
Less duplicate data
None
person who …
> Remove extra setup_logging

- CHANGELOG.rst
- requirements.txt
- setup.cfg
This reverts commit bf8dee99fd3fb56159ad6373bfb89ed74fe499c2.
This reverts commit 5f7499c08190d01b5ec1c153451600333c59383e.
(c) The contribution was provided directly to …
> Revert "Update etos library to version 1.9.0"

- setup.cfg
- src/environment_provider/environment_provider.py
- src/environment_provider/execution_space/checkin.py
- src/environment_provider/execution_space/checkout.py
- src/environment_provider/execution_space/instructions.py
- src/environment_provider/iut/checkin.py
- src/environment_provider/iut/checkout.py
- src/environment_provider/iut/iut_provider.py
- src/environment_provider/lib/celery.py
- src/environment_provider/lib/registry.py
- src/environment_provider/lib/test_suite.py
- src/environment_provider/logs/checkin.py
- src/environment_provider/logs/checkout.py
- src/environment_provider/webserver.py
None
Pylint complained about not using f-strings.
In order to add f-strings we would have to stop supporting py2
so I set a fixed python version to the one used in the Dockerfile
and reformatted all files.
Note that the logging module calls are not updated because of
how the logging module wants to handle it its own way.
We could just ignore the warnings from pylint and keep an open allowed python version, but since we are always running ETOS in dockers and the docker is python3.9, I don't see it as a problem to keep ourselves a bit modern.
Pylint is happy.
None that I can think of.
have the right to submit it under the open …
> Set a specific python version and update so that pylint is happy

- src/environment_provider/lib/registry.py
N/A
HDEL tried to delete a key that does not exist. Make sure it deletes properly.
None
Proper clean up before registering a new execution space provider.
None
(c) The …
> Make sure del works

- src/environment_provider/backend/__init__.py
- src/environment_provider/backend/subsuite.py
- src/environment_provider/environment_provider.py
- src/environment_provider/lib/registry.py
- src/environment_provider/webserver.py
- tests/backend/__init__.py
- tests/backend/test_sub_suite.py
- tests/library/__init__.py
- tests/library/fake_database.py
- tests/library/fake_request.py
- tests/test_webserver.py
This PR is the first of several clean-up changes that will be created. I do them in steps to make reviewing easier.
This is done in preparation for the external provider change that is on its way ( #38 )
By making the endpoints cleaner, we can make the external provider changes easier.
There are multiple designs, I chose the one where we
1. Reduce the size of webserver.py the most.
2. Make it easier to test.
Makes it easier to understand what is going on in the webserver.py file and makes it a lot easier to test.
Some code-jumping will be involved. With proper function naming this will be mitigated.
have …
> Decouple the sub suite endpoint for clarity

- src/environment_provider/backend/configure.py
- src/environment_provider/backend/environment.py
- src/environment_provider/environment_provider.py
- src/environment_provider/webserver.py
- tests/backend/test_configure.py
- tests/library/fake_database.py
- tests/library/fake_request.py
- tests/test_webserver_configure.py
This PR is the first of several clean-up changes that will be created. I do them in steps to make reviewing easier.
This is done in preparation for the external provider change that is on its way ( #38 )
By making the endpoints cleaner, we can make the external provider changes easier.
There are multiple designs, I chose the one where we
1. Reduce the size of webserver.py the most.
2. Make it easier to test.
Makes it easier to understand what is going on in the webserver.py file and makes it a lot easier to test.
Some code-jumping will be involved. With proper function naming this will be mitigated.
have …
> Cleanup configure endpoint

- src/env.sh
- src/environment_provider/backend/environment.py
- src/environment_provider/environment_provider.py
- src/environment_provider/external_iut/iut_definition.json
- src/environment_provider/external_iut/provider.py
- src/environment_provider/iut/iut.py
- src/environment_provider/lib/registry.py
- src/environment_provider/lib/test_suite.py
Add potential to register and use external providers
> Add potential to register and use external providers

- src/execution_space_provider/utilities/jsontas_provider.py
Fix improper exception catching syntax.
eiffel-community/etos#128
Fix a simple syntax error in the jsontas  provider in the etos environment provider
N/A
Syntactically sound code is always better
None
permitted to submit under a different …
> Fix bug in exception handling

- src/environment_provider/lib/test_suite.py
fixes: eiffel-community/etos#120
Increase the expiry time of sub suites to 48h
None
easier to debug when stuff takes too long and also makes ETOS a bit more safe when there's queuing in the execution space that may take longer than 1 hour
Database could get full, but it's doubtful that that will ever happen.
work with modifications, whether created in whole or …
> Increase the expiry time for sub suites to 48h

- src/iut_provider/utilities/prepare.py
N/A
Add the results of preparation steps onto the IUT object.
None
This will allow providers to add information to the IUT object.
Nothing spectacular.
(c) The …
> Load preparation into iut

- src/environment_provider/environment_provider.py
- src/environment_provider/lib/config.py
- src/environment_provider/lib/test_suite.py
- tests/library/fake_database.py
- tests/library/fake_server.py
- tests/library/graphql_handler.py
- tests/tercc.py
- tests/test_environment_provider.py
Preparatory change for eiffel-community/etos#22
Added a few scenario tests to make it easier to verify good results when implementing sequential execution.
None that I can think of.
Easier to verify that everything is correct when making changes.
None!
by me, under the same open source license (unless …
> Add scenario tests to the environment provider

- src/environment_provider/environment_provider.py
None
Allow the setting of maximum amount.
None
Will allow users to force a certain number of IUTs.
None …
> Allow users to set maximum amount in dataset

- src/execution_space_provider/utilities/list.py
#75 
Make sure we encode the password string first so that it is of type bytes.
The ETR also assumes that the RABBITMQ_PASSWORD can be decoded without JSONTas so we need to remove the $decrypt datastructure from that.
None
The encryption will work
None
by me, under the same open source license (unless …
> Encode password before encrypting it

- src/environment_provider/environment_provider.py
- src/environment_provider/lib/log_area.py
- src/execution_space_provider/utilities/instructions.py
- tests/library/graphql_handler.py
- tests/test_environment_provider.py
eiffel-community/etos#185
Upload sub suite definitions to log area
None
Makes the environment for test visible even after the environment has been checked in.
May allow us to recreate an environment if necessary.
Uploading may fail, but if it fails here it will also fail in the ETR.
by me, under the …
> Upload sub suite

- .github/workflows/build-push.yml
eiffel-community/etos#197
Add CI for the environment provider API and worker
Better CI will allow us to verify each ETOS release better
(c) The contribution was provided …
> Add CI for environment provider

- .github/workflows/build-push.yml
#83 
There's a high chance for a race condition in the workflow since it has to create two git commits. Resolving this by moving the manifest update to a separate job
(c) …
> Fix a race condtion with git and workflow

- requirements.txt
- setup.cfg
- src/environment_provider/lib/config.py
- src/environment_provider/lib/log_area.py
- src/environment_provider_api/backend/configure.py
- src/execution_space_provider/utilities/external_provider.py
- src/iut_provider/utilities/external_provider.py
- src/log_area_provider/utilities/external_provider.py
- tests/external_execution_space/test_external_execution_space.py
- tests/external_iut/test_external_iut.py
- tests/external_log_area/test_external_log_area.py
- tox.ini
based-on: #85 
Please review that one first.
Update to the new version of the ETOS library. This new version of the library has an update on the http helpers.
None
None …
> Update etos library version

- src/environment_provider/lib/config.py
N/A
Fix a type-hint
None
None
person who certified (a), (b) or (c) and I have not modified
it.
(d) I …
> Correct a type-hint

- manifests/base/kustomization.yaml
None
Updated to latest version
person who certified (a), (b) or (c) and I have not modified
it.
(d) I …
> Update to latest version of ETR

- setup.cfg
N/A
Rename the environment provider so that it gets the `etos-` prefix. The name `environment-provider` is a bit too generic and might cause confusion
Explained in description
Explained in description
permitted to submit under a different …
> Rename environment provider package on pypi

- src/environment_provider/environment_provider.py
N/A
Remove unused keys.
None
None
person who certified (a), (b) or (c) and I have not modified
it.
(d) I …
> Remove unused database keys

- requirements.txt
- setup.cfg
To integrate new features (OpenTelemetry trace id for logstash entries), etos_lib needs to be updated. …
> Step up etos_lib to 4.3.0

- src/environment_provider/environment_provider.py
- src/environment_provider/lib/log_area.py
- src/environment_provider/lib/test_suite.py
Generating an ID and passing it to ETR. Also making it available for other services, such as the new log area API
Not that I could think of.
None really.
(c) The …
> Add sub suite ID to sub suite definition

- src/execution_space_provider/utilities/external_provider.py
eiffel-community/etos#103
Pass ETOS rabbitmq parameters to the ETR
None
None
person who certified (a), (b) …
> Set ETOS RabbitMQ parameters

- pyproject.toml
- tox.ini
- https://github.com/eiffel-community/etos/issues/208
This change fixes several fields in `pyproject.toml` that were incorrect since the migration from `setup.cfg`.
(c) …
> Fix incorrect fields in pyproject.toml

- .github/workflows/docker.yml
fixes: eiffel-community/etos#305
Add workflow for building the new docker image
person who certified (a), …
> Add a docker build workflow

- src/environment_provider/environment_provider.py
When running v0 ETOS the environment provider would not raise exceptions back to the request_environment method in the ESR. This caused the ESR to raise a generic Exception with the error text instead.
The problem here is that the *CheckoutFailed exceptions can sometimes contain an empty string and the ESR would raise Exception('') which tells us nothing about what happened.
This problem also exists for v1 ETOS where we attempt to write the error to termination-log, but we will write an almost completely empty traceback that says nothing.
Created a new method that the ESR can call to have exceptions thrown up the stack.
I probably could remove the `run` method as well, but I don't know how much that method is used, so I did not want to accidentally break stuff.
Developer's Certificate of …
> Raise exceptions from the environment provider

- .github/workflows/build-and-publish.yml
- .github/workflows/main.yml
- Dockerfile
- docs/conf.py
- pyproject.toml
- https://github.com/eiffel-community/etos/issues/435
Python 3.13 compatibility updates.
person who …
> upgrade to Python 3.13
